extends:
  - pegasus
  - pegasus/node

overrides:
  - files:
      - test/fixtures/*.ts
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - ts-compat
